SET LANGUAGE us_english
--*****CREANDO TABLAS*******
CREATE TABLE VUELO(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	fecha DATE,
	matricula VARCHAR(30),
	id_aeropuerto_origen INT NOT NULL,
	id_aeropuerto_destino INT NOT NULL	
);
CREATE TABLE PASAJERO(
	dni INT PRIMARY KEY NOT NULL,
	nombre VARCHAR(30),
	asiento VARCHAR(10),
	id_clase INT NOT NULL

);
CREATE TABLE TRIPULANTE(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	id_puesto INT NOT NULL,
	id_categoria_profesional INT NOT NULL
);
CREATE TABLE AEROPUERTO_ORIGEN(
	id_origen INT PRIMARY KEY IDENTITY  NOT NULL,
	aeropuerto_origen VARCHAR(30)
); 
CREATE TABLE AEROPUERTO_DESTINO(
	id_destino INT PRIMARY KEY IDENTITY  NOT NULL,
	aeropuerto_destino VARCHAR(30)
); 
CREATE TABLE CLASE(
	id_clases INT PRIMARY KEY IDENTITY NOT NULL,
	clase VARCHAR(30)
);
CREATE TABLE CATEGORIA_PROFESIONAL(
	id_categoria INT PRIMARY KEY IDENTITY NOT NULL,
	categoria VARCHAR(30)
);
CREATE TABLE PUESTO(
	id_puestos INT PRIMARY KEY IDENTITY NOT NULL,
	puestos VARCHAR(30)
);
--*****ELIMINAR TABLAS********
DROP TABLE VUELO;
DROP TABLE PASAJERO;
DROP TABLE TRIPULANTE;
DROP TABLE AEROPUERTO_ORIGEN;
DROP TABLE AEROPUERTO_DESTINO;
DROP TABLE CATEGORIA_PROFESIONAL;
DROP TABLE PUESTO;
DROP TABLE CLASE;

--*****CREANDO LLAVES FORANEAS*******
--FK ID_AEROPUERTO_ORIGEN -->VUELO
ALTER TABLE VUELO
ADD CONSTRAINT FK_VUELO_ORIGEN
FOREIGN KEY (id_aeropuerto_origen) REFERENCES AEROPUERTO_ORIGEN (id_origen);
--FK ID_AEROPUERTO_DESTINO -->VUELO
ALTER TABLE VUELO
ADD CONSTRAINT FK_VUELO_DESTINO
FOREIGN KEY (id_aeropuerto_destino) REFERENCES AEROPUERTO_DESTINO (id_destino);
--FK CATEGORIA_PROFESIONAL --> TRIPULANTE
ALTER TABLE TRIPULANTE
ADD CONSTRAINT FK_TRIPULANTE_CATEGORIA
FOREIGN KEY (id_categoria_profesional) REFERENCES CATEGORIA_PROFESIONAL (id_categoria);
--FK PUESTO --> TRIPULANTE
ALTER TABLE TRIPULANTE
ADD CONSTRAINT FK_TRIPULANTE_PUESTO
FOREIGN KEY (id_puesto) REFERENCES PUESTO (id_puestos);
--FK CLASE --> PASAJERO 
ALTER TABLE PASAJERO
ADD CONSTRAINT FK_PASAJERO_CLASE
FOREIGN KEY (id_clase) REFERENCES CLASE (id_clases);





--***********INSERTAR DATOS************* 

--DATOS AEROPUERTO DE ORIGEN
INSERT INTO AEROPUERTO_ORIGEN (aeropuerto_origen) VALUES ('San Salvador')
INSERT INTO AEROPUERTO_ORIGEN (aeropuerto_origen) VALUES ('San Jose')
INSERT INTO AEROPUERTO_ORIGEN (aeropuerto_origen) VALUES ('Barcelona')
--DATOS AEROPUERTO DESTINO
INSERT INTO AEROPUERTO_DESTINO (aeropuerto_destino) VALUES ('San Jose')
INSERT INTO AEROPUERTO_DESTINO (aeropuerto_destino) VALUES ('Madrid')
INSERT INTO AEROPUERTO_DESTINO (aeropuerto_destino) VALUES ('Londres')
--DATOS DEL TUPO DE CLASE DEL PASAJERO
INSERT INTO CLASE (clase) VALUES ('Turista');
INSERT INTO CLASE (clase) VALUES ('Negocios');
INSERT INTO CLASE (clase) VALUES ('VIP');
--PUESTO MIEMBRO DE TRIPULACIÓN
INSERT INTO PUESTO (puestos) VALUES ('Principal');
INSERT INTO PUESTO (puestos) VALUES ('Secundario');
INSERT INTO PUESTO (puestos) VALUES ('Auxiliar');
--CATEGORIA DEL MIEMBRO DE LA TRIPULACIÓN
INSERT INTO CATEGORIA_PROFESIONAL (categoria) VALUES('Piloto');
INSERT INTO CATEGORIA_PROFESIONAL (categoria) VALUES('Copiloto');
INSERT INTO CATEGORIA_PROFESIONAL (categoria) VALUES('Azafata');
--DATOS VUELOS
INSERT INTO VUELO (fecha, matricula, id_aeropuerto_origen,id_aeropuerto_destino) VALUES ('2021-01-03', 'DQ', 1, 1);
INSERT INTO VUELO (fecha, matricula, id_aeropuerto_origen,id_aeropuerto_destino) VALUES ('2021-05-24', 'SC', 2, 2);
INSERT INTO VUELO (fecha, matricula, id_aeropuerto_origen,id_aeropuerto_destino) VALUES ('2021-06-29', 'WD', 3, 3); 
--DATOS TRIPULACIÓN
INSERT INTO TRIPULANTE (id_puesto, id_categoria_profesional) VALUES (1, 1);
INSERT INTO TRIPULANTE (id_puesto, id_categoria_profesional) VALUES (2, 2);
INSERT INTO TRIPULANTE (id_puesto, id_categoria_profesional) VALUES (3, 3); 
--DATOS PASAJERO
INSERT INTO PASAJERO (dni, nombre, asiento,id_clase) VALUES ('123654987','Miguel', 'A-33', 1);
INSERT INTO PASAJERO (dni, nombre, asiento,id_clase) VALUES ('987654987', 'Lucia', 'C-41', 2);
INSERT INTO PASAJERO (dni, nombre, asiento,id_clase) VALUES ('159321675', 'Carlos', 'B-14', 3); 



--*********VER DATOS************
--INFORMACIÓN VUELO
SELECT * FROM VUELO;
--ORIGENES Y DESTINOS
SELECT id, fecha, matricula, id_aeropuerto_origen, id_aeropuerto_destino, AEROPUERTO_ORIGEN.aeropuerto_origen AS nombre_aeropuertoOrigen, AEROPUERTO_DESTINO.aeropuerto_destino AS nombre_aeropuertoDestino
FROM VUELO
JOIN AEROPUERTO_ORIGEN ON VUELO.id_aeropuerto_origen = AEROPUERTO_ORIGEN.id_origen
JOIN AEROPUERTO_DESTINO ON VUELO.id_aeropuerto_destino = AEROPUERTO_DESTINO.id_destino;

--INFORMACIÓN PASAJERO
SELECT * FROM PASAJERO;
--TIPO DE CLASE DE LOS PASAJEROS
SELECT dni, nombre, asiento, id_clase, CLASE.clase AS tipo_clase
FROM PASAJERO
JOIN CLASE ON PASAJERO.id_clase = CLASE.id_clases;

--INFORMACIÓN TRIPULACIÓN
SELECT * FROM TRIPULANTE;
--PUESTO TRIPULACIÓN
SELECT id, id_puesto, id_categoria_profesional, PUESTO.puestos AS puesto_tripulante, CATEGORIA_PROFESIONAL.categoria AS categoria_tripulante
FROM TRIPULANTE
JOIN PUESTO ON TRIPULANTE.id_puesto = PUESTO.id_puestos
JOIN CATEGORIA_PROFESIONAL ON TRIPULANTE.id_categoria_profesional = CATEGORIA_PROFESIONAL.id_categoria;


SELECT * FROM AEROPUERTO_ORIGEN;
SELECT * FROM AEROPUERTO_DESTINO;
SELECT * FROM CLASE;
SELECT * FROM CATEGORIA_PROFESIONAL;
SELECT * FROM PUESTO;

--USANDO UPDATE--
SELECT * FROM PASAJERO;
UPDATE PASAJERO SET nombre = 'Natalie Volkova' WHERE id_clase = 1;
SELECT * FROM PASAJERO;

--USANDO DELETE--
DELETE FROM PASAJERO;
DELETE FROM PASAJERO WHERE id_clase = 1;
SELECT * FROM PASAJERO;